workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        # Định nghĩa các biến môi trường bạn cần
        MY_CUSTOM_VAR: "example_value"
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android release
        script: |
          cd android
          # Thay thế bằng lệnh build phù hợp
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
      # Thêm pattern cho phiên bản debug (tùy chọn)
      - android/app/build/outputs/apk/debug/**/*.apk
