workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      groups:
        - android_credentials
        - expo_credentials
      # vars:
      #     CM_KEYSTORE: Encrypted() # <-- Put your encrypted keystore file here
      #     CM_KEYSTORE_PASSWORD: Encrypted() # <-- Put your encrypted keystore password here
      #     CM_KEY_ALIAS_PASSWORD: Encrypted() # <-- Put your encrypted keystore alias password here
      #     CM_KEYSTORE_PATH: /tmp/keystore.keystore
      #     CM_KEY_ALIAS_USERNAME: Encrypted() # <-- Put your encrypted keystore alias username here
      #     PACKAGE_NAME: "com.codemagic_react_native"
      node: 15.13.0
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/android/local.properties"
      - name: Set up keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
          cat >> "$FCI_BUILD_DIR/android/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_ALIAS_PASSWORD
          keyAlias=$CM_KEY_ALIAS_USERNAME
          storeFile=/tmp/keystore.keystore
          EOF
      - name: Build Android release
        script: |
          # Set environment variable so it can be used to increment build number in android/app/build.gradle
          # Note that tracks can be specified when retrieving latest build number from Google Play, for example:
          # export NEW_BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks=alpha) + 1))             
          export NEW_BUILD_NUMBER=$(($(firebase-app-distribution get-latest-build-number --package-name "$PACKAGE_NAME") + 1))
          cd android && ./gradlew assembleRelease
      - name: Expo OTA update
        script: |
          npx expo-cli login -u $EXPO_USERNAME -p $EXPO_PASSWORD
          npx expo-cli publish --non-interactive --max-workers 1 --release-channel $EXPO_RELEASE_CHANNEL
    artifacts:
      - android/app/build/outputs/**/*.apk
